USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/softwinner/cubieboard1/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := sun4i
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a8
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := cubieboard1

BOARD_KERNEL_CMDLINE := console=ttyS0,115200 rw init=/init loglevel=8
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE     := 0x2000000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x2000000
BOARD_SYSTEMIMAGE_PARTITION_SIZE   := 0x20000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x40000000
BOARD_FLASH_BLOCK_SIZE := 4096

TARGET_PREBUILT_KERNEL := device/softwinner/cubieboard1/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
CUBIEBOARD_HARDWARE := true

TARGET_HARDWARE_INCLUDE := $(TOP)/device/softwinner/cubieboard1/hardware/include

# cedarx
CEDARX_CHIP_VERSION := F51
CEDARX_USE_SWAUDIO := Y

# DRM widevine
BOARD_WIDEVINE_OEMCRYPTO_LEVEL := 3

# EGL
BOARD_EGL_NEEDS_LEGACY_FB := true

# Vold
BOARD_VOLD_DISC_HAS_MULTIPLE_MAJORS := true
BOARD_VOLD_MAX_PARTITIONS := 16

# realtek wifi
BOARD_WIFI_VENDOR := realtek
ifeq ($(BOARD_WIFI_VENDOR), realtek)
    WPA_SUPPLICANT_VERSION := VER_0_8_X
    BOARD_WPA_SUPPLICANT_DRIVER := NL80211
    CONFIG_DRIVER_WEXT :=y
    BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_rtl
    BOARD_HOSTAPD_DRIVER := NL80211
    BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_rtl
    BOARD_WLAN_DEVICE := rtl8192cu

    WIFI_DRIVER_MODULE_NAME := "8192cu"
    WIFI_DRIVER_MODULE_PATH := "/system/lib/modules/8192cu.ko"
    WIFI_DRIVER_MODULE_ARG  := ""

    WIFI_FIRMWARE_LOADER := ""
    WIFI_DRIVER_FW_PATH_STA := ""
    WIFI_DRIVER_FW_PATH_AP := ""
    WIFI_DRIVER_FW_PATH_P2P := ""
    WIFI_DRIVER_FW_PATH_PARAM := ""
endif
